# Generated by Django 5.1.4 on 2025-02-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cars_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
