# Generated by Django 5.1.6 on 2025-02-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
