# Generated by Django 5.1.6 on 2025-02-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_cars_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='is_available',
        ),
    ]
