# Generated by Django 5.1.6 on 2025-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_cars_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fuel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
