# Generated by Django 5.1.6 on 2025-02-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cars_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='make',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
