# Generated by Django 5.1.6 on 2025-02-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_cars_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='make',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
