# Generated by Django 5.1.6 on 2025-02-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
