# Generated by Django 5.1.6 on 2025-02-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
