# Generated by Django 5.1.6 on 2025-02-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
