# Generated by Django 5.1.6 on 2025-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
