# Generated by Django 5.1.6 on 2025-02-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_profile_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
