# Generated by Django 5.1.6 on 2025-02-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='car',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='make',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
