# Generated by Django 5.1.4 on 2025-03-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_booking_cars_profile_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
