# Generated by Django 5.1.4 on 2025-03-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_buy_car_remove_rental_user_delete_cars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('bodytype', models.TextField()),
                ('fuel', models.TextField()),
                ('transmission', models.TextField()),
                ('mileage', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.makes')),
            ],
        ),
    ]
