# Generated by Django 5.1.4 on 2025-03-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
