# Generated by Django 5.1.6 on 2025-03-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='car',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='make',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='car',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rented',
        ),
    ]
