# Generated by Django 5.1.6 on 2025-03-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_order_booking_cars_profile_buy_rented'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
