# Generated by Django 5.1.6 on 2025-03-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented',
            name='buy',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
