# Generated by Django 5.1.6 on 2025-03-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rented',
        ),
    ]
