# Generated by Django 5.1.6 on 2025-03-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rented'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rented',
        ),
    ]
